sudo: required

language: node_js

node_js:
  - node_js

services:
  - docker

before_install:
  - docker build -t ravikiranyadav/docker-react -f Dockerfile.dev .

script:
  - docker run ravikiranyadav/docker-react echo "hello World"
